//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace Cyjb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttvartorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Cyjb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---&gt; (Inner Exception #{0}) {1} &lt;---.
        /// </summary>
        internal static string AggregateSourceException_InnerException {
            get {
                return ResourceManager.GetString("AggregateSourceException_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one field is found with the specified name and matching the specified binding constraints..
        /// </summary>
        internal static string AmbiguousMatchField {
            get {
                return ResourceManager.GetString("AmbiguousMatchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one method is found with the specified name and matching the specified binding constraints..
        /// </summary>
        internal static string AmbiguousMatchMethod {
            get {
                return ResourceManager.GetString("AmbiguousMatchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one property is found with the specified name and matching the specified binding constraints..
        /// </summary>
        internal static string AmbiguousMatchProperty {
            get {
                return ResourceManager.GetString("AmbiguousMatchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous user-defined converter found when convert &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousUserDefinedConverter {
            get {
                return ResourceManager.GetString("AmbiguousUserDefinedConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of parameter &apos;{0}&apos; and &apos;{1}&apos; can not botn be null..
        /// </summary>
        internal static string ArgumentBothNull {
            get {
                return ResourceManager.GetString("ArgumentBothNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values must be greater than zero..
        /// </summary>
        internal static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values can not be negative..
        /// </summary>
        internal static string ArgumentNegative {
            get {
                return ResourceManager.GetString("ArgumentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values was out of range..
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values must be between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRangeBetween {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter value is not a valid type..
        /// </summary>
        internal static string ArgumentWrongType {
            get {
                return ResourceManager.GetString("ArgumentWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter value &apos;{0}&apos; is not of type &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentWrongType_Specific {
            get {
                return ResourceManager.GetString("ArgumentWrongType_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound of array must be zero..
        /// </summary>
        internal static string ArrayNonZeroLowerBound {
            get {
                return ResourceManager.GetString("ArrayNonZeroLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array is not long enough, check array index and length..
        /// </summary>
        internal static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   At.
        /// </summary>
        internal static string AtText {
            get {
                return ResourceManager.GetString("AtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to open constructed method..
        /// </summary>
        internal static string BindOpenConstructedMethod {
            get {
                return ResourceManager.GetString("BindOpenConstructedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to the target field because its type is not compatible with that of the delegate type..
        /// </summary>
        internal static string BindTargetField {
            get {
                return ResourceManager.GetString("BindTargetField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to the target method because its signature is not compatible with that of the delegate type..
        /// </summary>
        internal static string BindTargetMethod {
            get {
                return ResourceManager.GetString("BindTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to the target property because its signature is not compatible with that of the delegate type..
        /// </summary>
        internal static string BindTargetProperty {
            get {
                return ResourceManager.GetString("BindTargetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to the target property because no get accessor exists..
        /// </summary>
        internal static string BindTargetPropertyNoGet {
            get {
                return ResourceManager.GetString("BindTargetPropertyNoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to the target property because no set accessor exists..
        /// </summary>
        internal static string BindTargetPropertyNoSet {
            get {
                return ResourceManager.GetString("BindTargetPropertyNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null cannot be converted to a value type..
        /// </summary>
        internal static string CannotCastNullToValueType {
            get {
                return ResourceManager.GetString("CannotCastNullToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not infer type argument from parameters..
        /// </summary>
        internal static string CannotInferenceGenericArguments {
            get {
                return ResourceManager.GetString("CannotInferenceGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection element count must be the same as current colection..
        /// </summary>
        internal static string CollectionCountDiffer {
            get {
                return ResourceManager.GetString("CollectionCountDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection may not be empty..
        /// </summary>
        internal static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was of a fixed size..
        /// </summary>
        internal static string CollectionFixedSize {
            get {
                return ResourceManager.GetString("CollectionFixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compare two elements in the collection..
        /// </summary>
        internal static string CollectionItemCompareFailed {
            get {
                return ResourceManager.GetString("CollectionItemCompareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified item does not exist in collection..
        /// </summary>
        internal static string CollectionItemNotExist {
            get {
                return ResourceManager.GetString("CollectionItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element of collection was null..
        /// </summary>
        internal static string CollectionItemNull {
            get {
                return ResourceManager.GetString("CollectionItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is read-only..
        /// </summary>
        internal static string CollectionReadOnly {
            get {
                return ResourceManager.GetString("CollectionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept action is conflicted with Reject action..
        /// </summary>
        internal static string ConflictingAcceptAction {
            get {
                return ResourceManager.GetString("ConflictingAcceptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject action is conflicted with Accept action..
        /// </summary>
        internal static string ConflictingRejectAction {
            get {
                return ResourceManager.GetString("ConflictingRejectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate type &apos;{0}&apos; not compatible with &apos;{1}&apos;..
        /// </summary>
        internal static string DelegateIncompatible {
            get {
                return ResourceManager.GetString("DelegateIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter with the same name has already existed..
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was modified, enumeration operation may not execute..
        /// </summary>
        internal static string EnumerationFailed {
            get {
                return ResourceManager.GetString("EnumerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument type &apos;{0}&apos; is not the same as the enum type &apos;{1}&apos;..
        /// </summary>
        internal static string EnumTypeDoesNotMatch {
            get {
                return ResourceManager.GetString("EnumTypeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested value &apos;{1}&apos; was not found in enum type &apos;{0}&apos;..
        /// </summary>
        internal static string EnumValueNotFound {
            get {
                return ResourceManager.GetString("EnumValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error] .
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional non-parsable characters are at the end of the string..
        /// </summary>
        internal static string ExtraJunkAtEnd {
            get {
                return ResourceManager.GetString("ExtraJunkAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base is not between 2 and 36..
        /// </summary>
        internal static string InvalidBase {
            get {
                return ResourceManager.GetString("InvalidBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find constructor matchs options in type &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidCacheOptions {
            get {
                return ResourceManager.GetString("InvalidCacheOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache type &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidCacheType {
            get {
                return ResourceManager.GetString("InvalidCacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache type &apos;{0}&apos;, did not implement ICache{TKey, TValue}..
        /// </summary>
        internal static string InvalidCacheType_ICache {
            get {
                return ResourceManager.GetString("InvalidCacheType_ICache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified cast is not valid..
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCast_FromTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target element type is not compatible with the type of items in the collection..
        /// </summary>
        internal static string InvalidElementType {
            get {
                return ResourceManager.GetString("InvalidElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lexer context &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidLexerContext {
            get {
                return ResourceManager.GetString("InvalidLexerContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the collection..
        /// </summary>
        internal static string InvalidOffsetLength {
            get {
                return ResourceManager.GetString("InvalidOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not a valid instance of ISourceLocatable..
        /// </summary>
        internal static string InvalidSourceLocatable {
            get {
                return ResourceManager.GetString("InvalidSourceLocatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1} is not a valid source range..
        /// </summary>
        internal static string InvalidSourceRange {
            get {
                return ResourceManager.GetString("InvalidSourceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified threshold is out of range..
        /// </summary>
        internal static string InvalidThreshold {
            get {
                return ResourceManager.GetString("InvalidThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same key has already been added..
        /// </summary>
        internal static string KeyDuplicate {
            get {
                return ResourceManager.GetString("KeyDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific key is not exists..
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; is not exists..
        /// </summary>
        internal static string KeyNotFound_Key {
            get {
                return ResourceManager.GetString("KeyNotFound_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified method is not supported..
        /// </summary>
        internal static string MethodNotSupported {
            get {
                return ResourceManager.GetString("MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single-dimensional arrays are supported..
        /// </summary>
        internal static string MultidimensionalArrayNotSupported {
            get {
                return ResourceManager.GetString("MultidimensionalArrayNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single-dimensional arrays are supported of parameter &apos;{0}&apos;..
        /// </summary>
        internal static string MultidimensionalArrayNotSupported_Param {
            get {
                return ResourceManager.GetString("MultidimensionalArrayNotSupported_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must derive from Delegate..
        /// </summary>
        internal static string MustBeDelegate {
            get {
                return ResourceManager.GetString("MustBeDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must derive from Delegate..
        /// </summary>
        internal static string MustBeDelegate_Type {
            get {
                return ResourceManager.GetString("MustBeDelegate_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be an Enum..
        /// </summary>
        internal static string MustBeEnum {
            get {
                return ResourceManager.GetString("MustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be an Enum..
        /// </summary>
        internal static string MustBeEnum_Type {
            get {
                return ResourceManager.GetString("MustBeEnum_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify valid information for parsing in the string..
        /// </summary>
        internal static string MustContainValidInfo {
            get {
                return ResourceManager.GetString("MustContainValidInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named parameter array cannot be bigger than argument array..
        /// </summary>
        internal static string NamedParamTooBig {
            get {
                return ResourceManager.GetString("NamedParamTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a generic method definition..
        /// </summary>
        internal static string NeedGenericMethodDefinition {
            get {
                return ResourceManager.GetString("NeedGenericMethodDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string was being parsed as an unsigned number and could not have a negative sign..
        /// </summary>
        internal static string NegativeUnsigned {
            get {
                return ResourceManager.GetString("NegativeUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any recognizable digits..
        /// </summary>
        internal static string NoParsibleDigits {
            get {
                return ResourceManager.GetString("NoParsibleDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors existed..
        /// </summary>
        internal static string OneOrMoreErrorsExisted {
            get {
                return ResourceManager.GetString("OneOrMoreErrorsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a Byte..
        /// </summary>
        internal static string OverflowByte {
            get {
                return ResourceManager.GetString("OverflowByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for an Int16..
        /// </summary>
        internal static string OverflowInt16 {
            get {
                return ResourceManager.GetString("OverflowInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for an Int32..
        /// </summary>
        internal static string OverflowInt32 {
            get {
                return ResourceManager.GetString("OverflowInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for an Int64..
        /// </summary>
        internal static string OverflowInt64 {
            get {
                return ResourceManager.GetString("OverflowInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a SByte..
        /// </summary>
        internal static string OverflowSByte {
            get {
                return ResourceManager.GetString("OverflowSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a UInt16..
        /// </summary>
        internal static string OverflowUInt16 {
            get {
                return ResourceManager.GetString("OverflowUInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a UInt32..
        /// </summary>
        internal static string OverflowUInt32 {
            get {
                return ResourceManager.GetString("OverflowUInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a UInt64..
        /// </summary>
        internal static string OverflowUInt64 {
            get {
                return ResourceManager.GetString("OverflowUInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one key parameter is found of processors..
        /// </summary>
        internal static string ProcessorKeyAmbigus {
            get {
                return ResourceManager.GetString("ProcessorKeyAmbigus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one key parameter is found of processors identified &apos;{1}&apos; of type &apos;{0}&apos;..
        /// </summary>
        internal static string ProcessorKeyAmbigus_TypeId {
            get {
                return ResourceManager.GetString("ProcessorKeyAmbigus_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key parameter of processors not found..
        /// </summary>
        internal static string ProcessorKeyNotFound {
            get {
                return ResourceManager.GetString("ProcessorKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key parameter of processors identified &apos;{1}&apos; of type &apos;{0}&apos; not found..
        /// </summary>
        internal static string ProcessorKeyNotFound_TypeId {
            get {
                return ResourceManager.GetString("ProcessorKeyNotFound_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor identified &apos;{1}&apos; of type &apos;{0}&apos;, does not match the needed static / instance..
        /// </summary>
        internal static string ProcessorMismatch {
            get {
                return ResourceManager.GetString("ProcessorMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing static and instance method in processors identified &apos;{1}&apos; of type &apos;{0}&apos;..
        /// </summary>
        internal static string ProcessorMixed {
            get {
                return ResourceManager.GetString("ProcessorMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find processor of type &apos;{0}&apos;..
        /// </summary>
        internal static string ProcessorNotFound {
            get {
                return ResourceManager.GetString("ProcessorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find processor identified &apos;{1}&apos; of type &apos;{0}&apos;..
        /// </summary>
        internal static string ProcessorNotFound_Id {
            get {
                return ResourceManager.GetString("ProcessorNotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processors have different parameter length or parameter type..
        /// </summary>
        internal static string ProcessorParameterMismatch {
            get {
                return ResourceManager.GetString("ProcessorParameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processors identified &apos;{1}&apos; of type &apos;{0}&apos; have different parameter length or parameter type..
        /// </summary>
        internal static string ProcessorParameterMismatch_TypeId {
            get {
                return ResourceManager.GetString("ProcessorParameterMismatch_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; has no get accessor exists..
        /// </summary>
        internal static string PropertyNoGetter {
            get {
                return ResourceManager.GetString("PropertyNoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; has no set accessor exists..
        /// </summary>
        internal static string PropertyNoSetter {
            get {
                return ResourceManager.GetString("PropertyNoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not found..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified property is not supported..
        /// </summary>
        internal static string PropertyNotSupported {
            get {
                return ResourceManager.GetString("PropertyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public property or field named &apos;{0}&apos; not exists..
        /// </summary>
        internal static string PropertyOrFieldNotFound {
            get {
                return ResourceManager.GetString("PropertyOrFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or field named &apos;{0}&apos; not exists..
        /// </summary>
        internal static string PropertyOrFieldNotFound_NonPublic {
            get {
                return ResourceManager.GetString("PropertyOrFieldNotFound_NonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; and &apos;{1}&apos; in reverse order..
        /// </summary>
        internal static string ReversedArgument {
            get {
                return ResourceManager.GetString("ReversedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from a closed &apos;{0}&apos;..
        /// </summary>
        internal static string StreamClosed {
            get {
                return ResourceManager.GetString("StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting non-empty string..
        /// </summary>
        internal static string StringEmpty {
            get {
                return ResourceManager.GetString("StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting non-whitespace string..
        /// </summary>
        internal static string StringWhiteSpace {
            get {
                return ResourceManager.GetString("StringWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Tristate_False {
            get {
                return ResourceManager.GetString("Tristate_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSure.
        /// </summary>
        internal static string Tristate_NotSure {
            get {
                return ResourceManager.GetString("Tristate_NotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Tristate_True {
            get {
                return ResourceManager.GetString("Tristate_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; contains generic parameters..
        /// </summary>
        internal static string TypeContainsGenericParameters {
            get {
                return ResourceManager.GetString("TypeContainsGenericParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type member &apos;{0}&apos; not exists..
        /// </summary>
        internal static string TypeMemberNotFound {
            get {
                return ResourceManager.GetString("TypeMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a default constructor..
        /// </summary>
        internal static string TypeMissingDefaultConstructor {
            get {
                return ResourceManager.GetString("TypeMissingDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true..
        /// </summary>
        internal static string UnboundGenParam {
            get {
                return ResourceManager.GetString("UnboundGenParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ambig].
        /// </summary>
        internal static string UniqueValue_Ambig {
            get {
                return ResourceManager.GetString("UniqueValue_Ambig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Empty].
        /// </summary>
        internal static string UniqueValue_Empty {
            get {
                return ResourceManager.GetString("UniqueValue_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unique {0}].
        /// </summary>
        internal static string UniqueValue_Unique {
            get {
                return ResourceManager.GetString("UniqueValue_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized token &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedToken {
            get {
                return ResourceManager.GetString("UnrecognizedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warning] .
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create weak delegate for anonymous method with closure..
        /// </summary>
        internal static string WeakDelegateForMethodWithClosure {
            get {
                return ResourceManager.GetString("WeakDelegateForMethodWithClosure", resourceCulture);
            }
        }
    }
}
